module.exports = [
['ohill', 'Orchard Hill'],
['o. hill', 'Orchard Hill'],
['o-hill', 'Orchard Hill'],
['orchard hill', 'Orchard Hill'],
['hampden', 'Hampden'],
['kennedy', 'Kennedy'],
['northeast', 'Northeast'],
['lgrc', 'LGRC'],
['haigis', 'Haigis'],
['design building', 'Design Building'],
['design build', 'Design Building'],
['design', 'Design Building'],
['southwest', 'Southwest'],
['southwest horseshoe', 'Southwest'],
['fleet services', 'Fleet Services'],
['whitmore', 'Whitmore'],
['softball', 'Softball'],
['umass softball', 'Softball'],
['baseball', 'Baseball'],
['umass baseball', 'Baseball'],
['curry hicks', 'Curry Hicks'],
['student union', 'Student Union'],
['umpd', 'UMPD'],
['goodell', 'Goodell'],
['mullins', 'Mullins'],
['fine arts', 'Fine Arts Center'], 
['fac', 'Fine Arts Center'],
['lorden field', 'Lorden Field'],
['physical plant', 'Physical Plant'],
['curtain theatre', 'Curtain Theatre'],
['farmers market', 'Farmers Market'],
['north apartments', 'North Apartments'],
['durfee conservatory', 'Durfee Conservatory']
]