module.exports = [
['ohill', 'Orchard Hill'],
['o. hill', 'Orchard Hill'],
['o-hill', 'Orchard Hill'],
['orchard hill', 'Orchard Hill'],
['hampden', 'Hampden'],
['kennedy', 'Kennedy'],
['northeast', 'Northeast'],
['northeast xing', 'Northeast'],
['northeast crossing', 'Northeast'],
['neast', 'Northeast'],
['n east', 'Northeast'],
['lgrc', 'LGRC'],
['haigis', 'Haigis'],
['design building', 'Design Building'],
['design build', 'Design Building'],
['design', 'Design Building'],
['southwest', 'Southwest'],
['southwest horseshoe', 'Southwest'],
['fleet services', 'Fleet Services'],
['whitmore', 'Whitmore'],
['softball', 'Softball'],
['umass softball', 'Softball'],
['baseball', 'Baseball'],
['umass baseball', 'Baseball'],
['curry hicks', 'Curry Hicks'],
['student union', 'Student Union'],
['umpd', 'UMPD'],
['goodell', 'Goodell'],
['goodell lawn', 'Goodell'],
['mullins', 'Mullins'],
['fine arts', 'Fine Arts Center'],
['fac', 'Fine Arts Center'],
['lorden field', 'Lorden Field'],
['physical plant', 'Physical Plant'],
['curtain theatre', 'Curtain Theatre'],
['farmers market', 'Farmers Market'],
['north apartments', 'North Apartments'],
['durfee conservatory', 'Durfee Conservatory'],
['totman', 'Totman Gym'],
['totman gym', 'Totman Gym'],
['butterfield', 'Butterfield Terrace'],
['butterfield terr', 'Butterfield Terrace'],
['butterfield terrace', 'Butterfield Terrace'],
['transit', 'Transit Services'],
['transit services', 'Transit Services'],
];
